#!/usr/bin/env bash
#
# Copyright (C) 2016 Sebastian Nohn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

PROJECT="$1"
CHECKMACHINES="$2"

HUMANOUTPUT="";
PERFDATA="";
OK=0
PROBLEMS=0

INSTANCELIST=$(gcloud compute instances list --filter="status:RUNNING" --project="$PROJECT") || exit 3

function processinstanceCounts {
    for instanceType in "$@"
    do
        INSTANCEPATTERN=$(echo "$instanceType" | cut -d ":" -f 1)
	MININSTANCES=$(echo "$instanceType" | cut -d ":" -f 2)
	MAXINSTANCES=$(echo "$instanceType" | cut -d ":" -f 3)
	ACTINSTANCES=$(echo "$INSTANCELIST" | egrep -o "$INSTANCEPATTERN" -c)	
	PERFDATA="$INSTANCEPATTERN=$ACTINSTANCES;$MININSTANCES;$MAXINSTANCES $PERFDATA"
	if [[ $MININSTANCES -le $ACTINSTANCES ]] && [[ $ACTINSTANCES -le $MAXINSTANCES ]]; then
	    OK=$((OK+1))
	else
	    HUMANOUTPUT="$HUMANOUTPUT $INSTANCEPATTERN $MININSTANCES <= $ACTINSTANCES <= $MAXINSTANCES."
	    PROBLEMS=$((PROBLEMS+1))
	fi
    done
}

function processInstanceTypes {
    for instanceTypes in $1
    do
        processinstanceCounts $(echo "$instanceTypes" | tr ';' ' ')
    done
}

processInstanceTypes "$CHECKMACHINES"

if [[ $PROBLEMS -gt 0 ]]; then
    echo "CRITICAL: $HUMANOUTPUT | $PERFDATA"
    exit 2
else
    echo "$OK instance types are OK | $PERFDATA"
    exit 0
fi

